name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
       echo "No tests defined"

    - name: Notify webhook
      run: |
       curl -X POST -H "Content-Type: application/json" \
        -d '{"ref":"${{ github.ref }}", "status": "success"}' \
        https://96d8-2401-4900-1f29-33b-a83b-1eaf-3682-dc7d.ngrok-free.app/webhook/receiver
